# This module defines the schema and data contracts for the JSON Quality Audit Layer.
#
# It provides dataclasses that represent individual check findings, parser conflicts,
# quality scores, and the overall audit output payload.
#
# Downstream processing layers (e.g. scoring, database ingestion, recruiter review UI)
# use these models to determine if candidate profiles are complete and trustworthy.

"""Data models for the JSON Quality Audit system (DEC-036)."""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any

# AuditCheck represents a single issue flagged by the audit engine.
# It is used across all audit layers to record structural, completeness,
# or grounding anomalies.
@dataclass
class AuditCheck:
    """A single audit finding from any layer."""
    check_id: str
    severity: str          # "info" | "warning" | "error" | "critical"
    layer: str             # "schema" | "field" | "section" | "evidence" | "semantic" | "cross_parser"
    field: str             # dotted path e.g. "candidate_profile.experience[1].start_date"
    issue: str
    expected: str = ""
    actual: str = ""


# MissingCandidate represents a piece of information that was found in the raw
# resume text (or OCR output) but is missing from the final parsed profile.
# Used by Layer B and Layer D (semantic audit) to identify missing data.
@dataclass
class MissingCandidate:
    """Information present in the resume but absent in the extracted JSON."""
    field_family: str      # "experience" | "certifications" | "skills" | ...
    resume_evidence: str   # exact text found in raw resume
    source_chunk_id: str   # chunk ID if mappable, else ""
    reason: str
    confidence: float


# ParserConflict documents differences between two independent extraction routes
# (e.g. Docling vs fallback Unstructured / old parser).
# Used by Layer E to evaluate parser stability.
@dataclass
class ParserConflict:
    """Disagreement between two extraction routes on the same field."""
    field: str
    parser_a: str
    parser_b: str
    severity: str


# QualityScores represents the computed metrics assessing the trust level
# of the extraction process. These are NOT candidate fitness/evaluation scores.
@dataclass
class QualityScores:
    """Extraction-quality scores. NOT candidate quality scores."""
    schema_validity: float
    field_completeness: float
    section_completeness: float
    evidence_coverage: float
    parser_agreement: float
    ocr_quality: float
    overall_extraction_quality: float


# AuditResult is the final payload generated by the audit engine for a candidate.
# It gathers findings from all layers, the computed quality scores, review status,
# and summary markers.
@dataclass
class AuditResult:
    """Complete audit output for one candidate."""
    audit_version: str
    document_id: str
    candidate_id: str
    audit_status: str      # "passed" | "review_required" | "failed"
    schema_checks: List[AuditCheck] = field(default_factory=list)
    field_checks: List[AuditCheck] = field(default_factory=list)
    section_checks: List[AuditCheck] = field(default_factory=list)
    evidence_coverage_checks: List[AuditCheck] = field(default_factory=list)
    semantic_checks: List[AuditCheck] = field(default_factory=list)
    missing_candidates: List[MissingCandidate] = field(default_factory=list)
    conflicts: List[ParserConflict] = field(default_factory=list)
    quality_scores: Optional[QualityScores] = None
    review_triggers: List[AuditCheck] = field(default_factory=list)
    summary: Dict[str, Any] = field(default_factory=dict)
